# Generated by Django 3.2.3 on 2021-05-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guests_can_skip',
            new_name='guests_can_pause',
        ),
    ]
